students_list =[]
#greatest element : 02_feb
s1 = input("Enter the name of student:")
students_list.append(s1)
s2 = input("Enter the name of student:")
students_list.append(s2)
s3 = input("Enter the name of student:")
students_list.append(s3)
s4 = input("Enter the name of student:")
students_list.append(s4)
s5 = input("Enter the name of student:")
students_list.append(s5)
s6 = input("Enter the name of student:")
students_list.append(s6)
s7 = input("Enter the name of student:")
students_list.append(s7)
s8 = input("Enter the name of student:")
students_list.append(s8)
s9 = input("Enter the name of student:")
students_list.append(s9)
s10 = input("Enter the name of student:")
students_list.append(s10)

print(students_list)